/**
 * 사도 이름과 대표 이미지 URL 매핑 목록
 * 각 사도들의 기본 이미지와 꼬까옷 이미지 URL을 기록하여 쉽게 불러올 수 있게 관리합니다.
 */
// 1. 성격 Enum 정의 (원하는 성격들을 추가하세요)
export enum CharacterPersonality {
  순수,
  냉정,
  광기,
  활발,
  우울,
  공명,
}

// 2. 종족 Enum 정의 (원하는 종족들을 추가하세요)
export enum CharacterRace {
  마녀,
  미스틱,
  수인,
  엘프,
  요정,
  용족,
  유령,
  정령,
}

// 3. 태생 등급 Enum 정의
export enum BirthRarity {
  ThreeStarEldain,
  ThreeStar,
  TwoStar,
  OneStar,
}

// 4. 역할 Enum 정의
export enum CharacterRole {
  딜러,
  서포터,
  탱커,
}

// 5. 배치 Enum 정의
export enum CharacterPosition {
  전열,
  중열,
  후열,
  모든열,
}

// 캐릭터 정보 인터페이스
export interface CharacterImageEntry {
  default: string;     // 기본 이미지 URL
  personality: CharacterPersonality; // 성격
  race: CharacterRace; // 종족
  rarity: BirthRarity;
  role: CharacterRole;
  position: CharacterPosition;
}

export const CHARACTER_IMAGES: Record<string, CharacterImageEntry> = {
  "에르핀(왕도)": {
    default: "https://i.namu.wiki/i/7YejFTDDInzNIkPxehqHdsyta-DG_ZrwkG_Kbszs57xJzmqHGnWSwl-eXmDIKznIpk9CZPgXDm2-roewXlttJEsaU_rrNDPdkibxNhz38YFxY3GfTs2Xu22CUXc0U7SK45qpHWG6M6Xrr_OQkNGeew.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "마요(멋짐)": {
    default: "https://i.namu.wiki/i/5cQDBm-fWN9C_l6aZVbxpFYl11cb1-j8IVglEqYVSMV3xHrGwPVdh8WsKsjhZzpHwGlV34og604OsR8t5G-wBhnKgvvkxK6d7n6v04bOg3vOVf-wfOEGnmBUiFPFCz_TnWKHA8y9cs3abZYsGVxV5A.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "에르핀": {
    default: "https://i.namu.wiki/i/ggYdw4v7LKtvdVdsnxq3pP_O-FJ4qFqyYlHpmQ6e9b7vO-91eJb-MM_xW-tdXSFnelI62Ym2f11rQRzM8wSXCQgUP6ClA9rKU2vn66vjkOiHlxUygwZ6-kEYKw3T-vSPAI-nZBYGRQWMoqt3Cqi1rw.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "캬롯": {
    default: "https://i.namu.wiki/i/xEAiicZEn8bts_YvHNafidWovpFVEiKnFBNOqEqEm2wN6EJpnO41hYA8wUMv7khBvCTaQJc0OTZ8cW6yt-AeG8Kxf_K8iJ_9nFnCDs3n5e--bY6YVLxfB7xpvmuy__rCSNBIiBMbWKlo8dRjbVWNQw.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "큐이": {
    default: "https://i.namu.wiki/i/Ma7bu56w1wqPbg4F4zypH1xb1GoAi6w9BItlA7T1s--SK0sjp4eiexIzx9LT1-WjG0IvrOO3WHVl1uI7_XXl34z4mE-47MlfoSdClK-JwyE730ZwRXiiI1xpJFHu9p_7vcsPcD6lQO6faeiEoGhv_A.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.요정,
    rarity: BirthRarity.OneStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "란": {
    default: "https://i.namu.wiki/i/53l0JMR--UTi61DtQiSi5QePpF1Zn5hWigmajgs-onOhUnLBgjfHzisuRE4-_J-8U7Kd3x-Df4DoPnhEpe0NFZMLhxcAXxOsvl1slAB6qPv-Jh2jcjLxujDNE_SIjuDyEhSvm1UaAtavYa5VGHSNJQ.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "델리아": {
    default: "https://i.namu.wiki/i/MEA7U-ajQB-v_dJzLAyKM2zCCvojfOzryLzZZF7AfbTr4SilTT9E20BxxAL7G_hAgr4R3J-o_9spRBs6W37Avn3-cQAzqiDSloHnmg7qDCWqr_D6YLfP9a7YZ7VLgeVZ1VR9_NBHVrEpEikrY6Ksig.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "마고": {
    default: "https://i.namu.wiki/i/MG7b51QwV0mqdt7R75NpJKuuue9GxQQkI-buowzppyIQPUglXGy5jlMI2g_WaxmIRpLAZCBdXPP_7Lj5-FUts5rzcsNaXTquRJg7hk3Q8r66pBY_8YfOKmTkMcE4yxFgWOQeWjvuwG9nWj2UKq8iYQ.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.수인,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "이드(재활)": {
    default: "https://i.namu.wiki/i/lWwI79F1Mhw1Bqle49KxSLp9zMUsk6GgJU4rX63aGKBi_WXqe-oiNa7CteT1SiKtKgbvDnbGlPmleiz5QTtftVddCpJ_uhJbymD92MbhbFzUfYy5Av0hZgOSI48qj3IMnW5a0trnKe7dhoWL9a4aeA.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "헤일리": {
    default: "https://i.namu.wiki/i/i7h4NHqySfUi4A2YFTxftbqyqFk2NOy1GLRlIEkgBjPFFq3RSzZBcQ7Hss81w-ZU3OEu8nyINIBczyukjVln4vNGq2FGL3hKwFBdjRzej5VataN4Tn2XJF1HL0h_YlbUTQ4N667_DrVwPLtJrsNXYQ.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "캐시": {
    default: "https://i.namu.wiki/i/S7smZeY7bkd4HbvObj8VRfIzYVZgiHZriOnX-Og_Zb_zf3gPaSYMxZYQkhGf8qSlNZZE1uVPZfbflP6_YTM_VfWCH1BQ6z8POZvi8heWbqeYiSdPZEswhgSY1k_fzNJI66deOFam5N0Tg6XF7WRfwg.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "로네": {
    default: "https://i.namu.wiki/i/Mias16Qx2FsrrciJ5MnD3iqWIEm9NGTVKHIt6na8n2WuYOWT90spUkMVOrLPtuL060kf9l31yQXtetpyH8pczaZyTe8RHdl_n25-xGzh3-dJJaKeYaD01am_RrvNgzHMMrl9r64oQrf9wARQ9_RjYg.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.엘프,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "페스타": {
    default: "https://i.namu.wiki/i/ohOThga0XTdPldyQmm9AVtRTnGqHoxzgpIc712PgPlrRCJubCFzYOyyNE5uj11yR4yJynk6EVc9iZEoxyD51qkibud7m6EyEVnZNreSocJFnFgdoUQJtTWHBzHXy9fDzGlAYGXFFeWjioYsCB7xziA.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.엘프,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.전열,
  },
  "알레트": {
    default: "https://i.namu.wiki/i/uP9Ct4Xrmnk8mQNnXZaYQgmmrZg-PEyHs4-pvTSfaB8m5NZ00dek67f2-vfx1Uo2T944wG2ZneRIn16nH4ls6lOy-pCEbXDl29iVFdJ9Fedr2nPp-CEiCMR45gvOQmsUvgBU4iHhpL8BDbTeCugvdg.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.엘프,
    rarity: BirthRarity.OneStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "라이카": {
    default: "https://i.namu.wiki/i/q1o5hkc4ZfTwmQLl55aYUAuZaGCIPds0CwhfRVZKzrD2bc0z4jdswIoOCIyjr2Ltk-XA-Mt5mvjUmWe8TvtOFXU-itgCUFh3_bJgahDsnj_PNLvPAhKTiMHnGwGEISiIY33DtxziXxxyu9xrICJeHw.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.정령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "나이아": {
    default: "https://i.namu.wiki/i/xi0zX6ZXpKZTs5Vdz7-xe86u23NnhIW_NpKow1emX6gXaQjqPQKn6hv2sBwEW-WJ1Ex7yh7x-jmvSZEOazemCB-w2XbHNrWepvB79H_2ya8hg4dOLwRbORx7L6aCCtWhYIzXht8NlDiO2pf0urhqPQ.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.정령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "아일라": {
    default: "https://i.namu.wiki/i/jjzkaQRHeblwP9K1ZUk33g7iZII1fGq3ajJp2hRgLn4-SOdEasu0pZfED9vGspmYlG8p-QyiX17AnNpdm17RXZsO4pA2lAx8CTdcvKkSxlmZ9CJbRAn95Ae_Fw4UmYu03Q6cT358TukwW9t_qphisg.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.정령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "뮤트": {
    default: "https://i.namu.wiki/i/ACBKk_TV9ok_chEaQvkHlhog_F5ALfuRbpIEL9-32TyCiMljEOsSAqniFFsfV-tI2SU7aP-w7531Vb5AkcxtXZANfUwqeL9b0I_UB_Iq2pytELnDB9IyzJhI-JZRK8BXDSuIwoh0GwQ5b0Xfm7GJBw.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.정령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "빅우드": {
    default: "https://i.namu.wiki/i/EfqcEoZt1m9zvrIkwO1PcRoaaHNt4iJjZJqVszaIOwPVDgyq4dmFV3yeHdsRljj_Y0ChNBre_4VSX-AuFpMpQEWXi4Jv7zxwSEFLypS83KCh1l0mfawL3k5G8hATSfEVSPf3x9Z2hLmlVoAOcbngyQ.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.정령,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "가비아": {
    default: "https://i.namu.wiki/i/OVAIni3QWQSRfH0yj2QhJWxL3LkyorbTJiLNGlYthZCdBTq7yffY9iiyO_5BPJy9A8qGcsG0BweTaRarhhKuSKSxDgOHMSJHsdKRboJ3MBCR7SS-ICsAJaF1Kenxh54k3_uv9UxcHBPHLqVFUDGz3A.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.정령,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "스피키": {
    default: "https://i.namu.wiki/i/cGl4Aegg8htOyyMI5scDJt_hGSEyykRWtCUBG7Q5X9s1wMJnzdiI4v1uevXOkqLh6a6228V3gl2N8L74PxtafryU9cdDxJ1vhUhFuYb3z8KPw-WXK7QJptYLGv7RixJ4XgK4wdhqgvU90Q9LTG4vSA.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.유령,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "사리": {
    default: "https://i.namu.wiki/i/kM12L_oEB9BAu6sfumvskoXemLWrFB8vwunp8zlFSc9EW-XknBrthKQo4Qp7glX8vEJA69_eO8V_nxA6xpP7uXAx9gXGpKY6RfBeIMx8wb0l5EC_NJZJ-xRTzzrM4d0rTxk3qhrjxvzHHlIBIqaumQ.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.유령,
    rarity: BirthRarity.OneStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "비비": {
    default: "https://i.namu.wiki/i/i4TGJ89cHhYBXviZKFUgBWjN87HDs06jIOCeww_1XIlhVEO1YFXIlt63t6-CADby4_1p3DLtBO_WAWFr3S78ki02B7ue9tNrhmgedJ1cI0eFRqCDALfMhrhWDoMr01LPf3qhKuiS61LLgfwdcdnkIA.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "다야": {
    default: "https://i.namu.wiki/i/yExTbX0JQonAlvQAErupYvwUTNA5e9gSiy_AQ07ls21aTg1nAYguUSqkW9xnY22yo76yAtEoV0UzF2KEWzLvKDRBzTGu8XHb8ytjry--cBbq7l0a2dRPe9nnLXIYnzwu5nPHUGxpXPXtEWOFvU2fsg.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "오팔": {
    default: "https://i.namu.wiki/i/-xWnsU0RuIlbOyIAsG2m6NAtWKHHSSui6QmGsGkI5MB3i8LaGAb_MmXJR1xrAZBuk3nm4CarEdJ6c6aok3XuMcXZgOvtVIzANLAVavnj8ZJ22MQThVPO1hKa0cEr2WWXOnHi8qdaIut8ry_O8wWv1w.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "셰럼": {
    default: "https://i.namu.wiki/i/dz9ApD6uWnc4tBX5tRUqaGtfT7fF2i9hOTzh3PDqH7Lb2cup1ml6kXdjWBqGZoXzCXpy017OxWn7sCs6WfyN8MG7JWqwwybHViEGI3OEGr6eAf-5TOOGl3d1QnjJBynw3Ep9UGj7rkTHmj5zdwjXbg.webp",
    personality: CharacterPersonality.순수,
    race: CharacterRace.마녀,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "리코타": {
    default: "https://i.namu.wiki/i/hsTcKXMNmPF7hHZvm6klWBUZ92ZIVAX7VyQ226CZrqhtUXqY4bNAxjtN_GAIQKH9xJnjynTY4NK-wH_eYnoIysSdzGCo3OlplalrbioIl-zSID1gzAdbBCe9ihc624co6llu38sVcfoXZybmVvP3dw.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "칸타": {
    default: "https://i.namu.wiki/i/dN1_p18hwEeFe_E0XhMo1-Ga4WKYcmLMO0NPgnMtnLHKMiiqoyShZM9b0WJhmiT-v7d6Be9NBuWTzDPYWQF9QPskxRu0RF_Bb4VVVkAQgv2jrsRCXYgyOV-08xnYMwOdlRBdpCmpV7sZoqLIi3eR8Q.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.요정,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "파트라": {
    default: "https://i.namu.wiki/i/qTuXCSON9BCww3ON7xd_9ssEBhZfdLf1iJxXKW4-bS5ui4lH5FQJOaSXY3BzP0GTWFe1_BIFNoH1JkBdlKN4GhOe24lhr-a7DONw0x6eofLiXjNPswa_W2ZD0cmhVDkrN1HDcQsigzv9RBu3gy5g1w.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.요정,
    rarity: BirthRarity.OneStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "디아나(왕년)": {
    default: "https://i.namu.wiki/i/UFdg_HECqIS46k5hEsyjOykzJXapHkgDvkQpFQsaVVHgLHPraZ_6j--wexBXA43yln9dsUyoML7Da1ik-TqfQEfjXDX-ULCANHyrLbgpadnsOnPtXB9frC47Nu-yedeGhVE2E6lZkr_Te5l2u2DQMg.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "베니(베니)": {
    default: "https://i.namu.wiki/i/D56KxXoSe9okyIB9YinnNvD2dndLB8mCCfPlJpheeQtZvW3XzfXmspP9Nd-e9Mpw4EWazZcPrQSiIghLgH4sAlhnU76SpnDEcN3KLQu7ydzSnS6HAnBhDiqOy8sp1DGaRfI326_wEtfumgdUMKZVQw.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "그윈": {
    default: "https://i.namu.wiki/i/N2XXWSZ1bKFCI3JiI8oZryTeY8ClJE8vrTnD_x5Aef1dgK2Ig0aRVDdYFW5OTgHVE7KX4R5XKHX88E7o_zarUnE69rzA0FfrEgn_LzoFabGyehBDKQugG5WtUWSjP6aDFmZmOvDiWB8Vj1EeJYmwLA.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.전열,
  },
  "코미(수영복)": {
    default: "https://i.namu.wiki/i/33TKq1jk2hBeH2AhDSjuFVwGDGAy3aZlmazM6wr2PBfr12EdYXPXdXybSfwmLlkR_h4y2PzDu1ap4psv7x0wx2PrFUHGmM6JWowKv9SoeFaReafLcezQIfqOm_9CIEHdkxsPyDt0eHP0Ip6g-Ax31w.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "베니": {
    default: "https://i.namu.wiki/i/tpARfuOUU7pbDkKY2vKHzjRL-5zXRiTI5CswC67FAnCQp8NLS80JXjoYUN_3bq4Oh5FolEVqyexh3jyh2M48cN9r_u64ghP_lX8u3FngSl3Ih0l-6tUgne1q6Bp5-efWv8fiMVz952No-LgYvzCUAg.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.수인,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "이드": {
    default: "https://i.namu.wiki/i/sZ6BiKDE9qrxYuyVfE9H6qc9N6kz0mdiJZ9sNCON9jzaFXiHVvN_CZqrwpTfOt_--uG8XzQsmYn0f8_nsBSs6GE0AVWrToyYE7OHT70yoH51bkpltLY2OkYM61c3dmr0I-8AQyf7gJ6OZi-GdEfauA.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "엘레나": {
    default: "https://i.namu.wiki/i/34Q0WKu6nB2tpHoNr2vCy2Lgl_nh-tzoZHGNMg96nWEzyWCr1VfMz_1G96adxeaRULLStdV_2THtmBaztV2ASZi2URk-rRY_3WEiKugTS3NlrSvgkodpqNwHa-w8iM9uZPvRVdxGf8b6HtQPnPCR0g.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "아이시아": {
    default: "https://i.namu.wiki/i/V9roRD-f1Xl4Ry7DpnF3B-bv0pwXwlQZoos78q64kbT79Wuq4AZBSWSJYnSnPQFjX04WVpKNfR-xAhdRY0iTE0LEZlEJE-wvTrNsMkNDxVB10Z28NdfT688mMgFGHL9p-yFurV4locFCihMSOJ-Pmg.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "아멜리아": {
    default: "https://i.namu.wiki/i/34Q0WKu6nB2tpHoNr2vCy2Lgl_nh-tzoZHGNMg96nWEzyWCr1VfMz_1G96adxeaRULLStdV_2THtmBaztV2ASZi2URk-rRY_3WEiKugTS3NlrSvgkodpqNwHa-w8iM9uZPvRVdxGf8b6HtQPnPCR0g.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "레이지": {
    default: "https://i.namu.wiki/i/BUe2s73Wq90Tq2bOOdyAes7wCS7rrIVBhhyzx6Ydfk4ggYhfDQVE2z0D-B8d-yCheADRggVaoOKa_3lcbd_iOq_wZBNh6M7EQhl8YNr9iFswPpdzIwftufSwd99UNbHfkCqem8dDV2SnrTFM8mL8LA.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.엘프,
    rarity: BirthRarity.OneStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "실라": {
    default: "https://i.namu.wiki/i/X_GJroBqgtmAqzx_t1D7aSBJ2ioJQQtyG4bWNWd09dQWK-zOlpSaG8M5zevsQrh6I7J9isHIPfeUElE9X26ynhjcVorIdlc4L8GeXpqifd2DUbmwx0e8lJ2QfHvkwQVtWQc9erd_yDsFM35ev7FORw.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.정령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "잉클": {
    default: "https://i.namu.wiki/i/aUxXMbZ4V4RfLOgg7zhvgzY3dCpAuihP0l42NUgNu5ZxWzf55hHd7DCM6QlvJR9EPPv1ZsxYXRta55z7kMNq2BCfv0uTf-g98EYV9A3HrL9xQPOx4ZhtOqAJsQZ0AT4SPX6vOcCaYmg7oorDJebAJg.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.정령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "시저": {
    default: "https://i.namu.wiki/i/ZKDy1pQm_h5p9nBhhac9jmS-v1fege-Emq0-YJ7CqP8eNBiS4bMwp7n-8pIAT27MmwgpF1FYxg1pufE4h24f0nj3BjPCtyxAMShhyF-cXUPJfEErbXmVzXgMZrN7_hEmJMwJXgW-JbtM7YdyYlPIpg.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.정령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "멜루나": {
    default: "https://i.namu.wiki/i/pAqhvfBT8xvQjFrBCXm2K_m-vgLp8ijOI_gfs7zpPwuLflQ_ti8Tad3DUtZQ5Aq0atekCQlytghFRa7KE0ouNadLv0hGihLUKj5X5Ozvh35DIgk9f2NGCH6qr2vJhtO5XX2vf04lil0JoezlIVuP8g.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.정령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "바롱": {
    default: "https://i.namu.wiki/i/oO4nAUIJcz1_p-0qWA74rTLwA0Ujl2-Wsprft-b0dnrohMhu7eSh46N9hlDq2J-VF15PrW8sax5HFjmgyB3Km9tk_ln7Q_gjsh9UiV5BalLpBAm_ILvo3j1TOL3HjQAYgwhBk740X4qYCNZxw3_-gQ.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.유령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "레테": {
    default: "https://i.namu.wiki/i/oNQXnl-an9IkNuC5v9vAmVVgqthI_WeOcL-hz_IYfvY3m8TZe0_ZrkR3UEO0E437kbXhb2IWIPws7cURbxzGcZpWS-PSSfAhgP4yv6DRvQ_zJ86sKMBnbaj-HrDMFIAHmest4AWij2xnaQtMGHguwA.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.유령,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "에스피": {
    default: "https://i.namu.wiki/i/lVjjeHbpL_8YXHG4orlXEnyGLOYchWyvA8EpNO-_Ngd9WzleZHBJgCscqXhdnr0hV0q4NzoIAbqOlDDwQ2G1L6k6vxVEPTO8NnBFrjjA4xXHeMJOuGJSIzKzm6v2SrbGapP0pwp71X2rG459BKwsiA.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.유령,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "제이드": {
    default: "https://i.namu.wiki/i/MQdjjdNSoLyxhBb92RUZcYN3tS6v3Vk7RZbnba7fi7uIVoSsiUxsd7ayQs8d01fw_v0aRNGni22pT-hVQXaMmC1BMG_p1GYXnkLLESTMHo_OOTg0TJG8D6Gle5YdBfO6QAvFYbDqOygi149fEz8Ajw.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "아라그리아": {
    default: "https://i.namu.wiki/i/0b-uIKcJo_6csy-W1vSGPXHwyix7ju6aLX62N6z8LLGdqxNBxWRPIrX1B3psDiFuzCtsNHh8ICjD29gYVM35tvnNhg66bC7MA3-8VE4zvQN9KhPXcQ6kD9_yPiaD6_CUjs9VCgiuqFtkW7B8x2OCWw.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "아야": {
    default: "https://i.namu.wiki/i/6T16HVlP35DvjCmw0edLHogvS_vMq63O31Ey5Ipy_QpIJ0pE-2iJLGfRLaniiCOmI68sgqZgtgk01J5MIiUcOXHVrfSasJkdik8u1U9X_QAmbNdk32J4C9Ra6ioQN8M0H717lCQG8ZX1XpeGHoqNcA.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.마녀,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "벨벳": {
    default: "https://i.namu.wiki/i/9NYkeOVGbI3yfuBIte1LqeFOjzSd5tIga31BCxl743INhwqQYfzrOQFEs8x7zWxutoyoRjIjwK8EfxXBVaGo21EgaMIDRowXM0q96IeVSYeRYdbo7-hvjBAGhfv1Yt8-TDVbInu0VncyFqq0NrhQKQ.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.마녀,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "프리클": {
    default: "https://i.namu.wiki/i/sxYIep1_XX6yFSgGJAmZvr9uF7hN6LC2JbXSDtoxKb8oLpOzg3s3NIO9O-8NUV0-v3OaHUcvELtTJyyS6f_kyL_j2KaXo98zmLkXOUeYXB4DZDmcJOndGt919GM3TfC5pAHacNk3Z6F9hN6BMDJJiw.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.마녀,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "피코라": {
    default: "https://i.namu.wiki/i/399ulMsrl1-e5dNdReSn_A3uemBKb26gpcI_ChqibPxxdpaeKSzUySd9W8CHLI4Pl8Mdncs4ECtTOYPA1Nnt6TAH2gFpEPNOfjhe2K0AX7AdmkDMjrGmn2HV8ROt6EEhnpDMvspPTGjM0P8Xzt2DQg.webp",
    personality: CharacterPersonality.냉정,
    race: CharacterRace.마녀,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "클로에": {
    default: "https://i.namu.wiki/i/M1uF4ixAeyPLWXs6DNpLDdxZTQ1f9SVo8RNb6l0abIKf-1wsKP1yRvwBWVXRqLYn9mBwkIBaIm3tT-Qe89ATJxRtFjV5rLTw5f0OurL4oNxU7jmL-8L-RgOYKhpSJRlFCYKMeUhJKTU0uswT414m-w.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "네르": {
    default: "https://i.namu.wiki/i/rzHY8bYJctxUs_568dbPUiJtT3NqHyaoEPsq9kSHuTRYAdK2HChF1jlEgFSeEPGKpr6aOAAHToLkXi7eTmfFBbVzeNSvfzu39m9HGaKtZP6ZB8QHkZPptusiennFCZhXcfan0Bf-QcoUdIxU1WIYZg.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.전열,
  },
  "폴랑": {
    default: "https://i.namu.wiki/i/YDfWUmQ3U_6hpcUFkFHjVOtg-K2qS5vGTV4FCc3hOk8O_wMjDRtBSMdb_Uef8buio6UbCbSe3w_yR-dm-iaWhM2mE-54ayTCepvIoy4-f6HfJaDkZjV61pdEk6wxEPvg0cnZgRvgz7VEtmjxMB28WA.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "마요": {
    default: "https://i.namu.wiki/i/1p7lGcYPczusTx0__ZLEr0yrmm4qcWlJJ7viK_XO4brvbHFNTiB15fx8Yul0Rx5rszlTPyDDMVrTL8gRql-V4wqQvMwgPnP8rpjvrhe6QzQi7mLIJ9lBiJqwoFQGDBg3XOW-uioBesV3ft1VGpI1fA.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.요정,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "티그(영웅)": {
    default: "https://i.namu.wiki/i/Q9Cxmp2NqZK7HQcazM35ceWrfFGxh5mq4_ze8f2rncR352k0MufGhVHoVEC_guguBiSCyxyC7L0TlWhOpFVxtQRkxwgg7V-JbJRmBZNiP3JesnMgapRH8WZwsGenKQJ94Yq_wNU1OFpg9jKypmaNqg.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.딜러,
    position: CharacterPosition.모든열,
  },
  "디아나": {
    default: "https://i.namu.wiki/i/KuuJvAIi4iORF608L3MO9JxEzlOpqpPLZ1OGlhTnjLm-1g1XfSufcd8XHrs1Aa8GNsoOZUUELnv-2QEcUp9W36_wDhaWvJx3AnZFNoVdUtLYjlGPYRG7XYtqPhOUANHlJGSA210NPUqCfEBaukmY1w.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "유미미": {
    default: "https://i.namu.wiki/i/HaQ-Rhza6fOo6fdiKg-TBoodgltVEPeQD3ELLXystAFIVYssKJ48XRd0bvjwAq06C5QQGEatjcC6DWdT_AEUlnaJrgGCbQBmDNaSjw6dEQJ-pwkjB-txfdG7w1x64djSFvWSi6V4XVWVrJo9BpuymA.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.수인,
    rarity: BirthRarity.OneStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "리뉴아": {
    default: "https://i.namu.wiki/i/d2xoKMUNR3AjoimlUONdbIVUAl-cG_XdLmRWfGQc4WJ1Jd6zlgRzV1UXemtUebygyQhENRJsvrePghZW2UBUmCTk1ll1bhfOZKE7D8AwNEaEgFMDAB3sCI2lzEBnx3iz4NfEOhpHYyMMrTejcfFqsg.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "헤일리(멀쩡)": {
    default: "https://i.namu.wiki/i/lcp_1dOtVFeRkJdVSkQXQjXnMJC03stNmMz1KB0APtic4oFc6cv6wlZMTk15Xvz008lgTTpXSR8Xy7vZOYgIU1vMinZz_-8y5F0jm-NnU4r_fpB2jWcGQIj8vmLh5mzyLFTUy24rXu10UW52-zFZFg.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "하이디": {
    default: "https://i.namu.wiki/i/2PgZMNjQ3UxF_r7vPQcFSiONsgnSxUYu1Jnj6XBWbU_XaXh6egjCchVhp41csX58P_EajaQ7SyX-oPpbMg6d2Pk0O-Pa2RU1kZmn2ghYkjXJR-odYrwpG1gkM_TMrFV-ihFS6QbDrbEUS8m-BgY3Iw.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "마에스트로 2호": {
    default: "https://i.namu.wiki/i/X1tJNYXZUXq6AMZdonmNcIiFeB4Yzboy-31NvPeMeH8cFXDCC3CZj9dW0ClFYwp7a4BgJRdd6Zt18LEpikdUOQjHCWEWwfd6zMRpZkZ3IhE2bKIbxJx8UrlAlcJ5XTbST3IAmYJiDsGvput2m2fW_w.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.엘프,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "이프리트": {
    default: "https://i.namu.wiki/i/ayH6hJF5NoKzIvWr9stLeCUoqrKGZAkdoEeKceD4xSAeRWYtJf4cAJMJgj2AjnCU9ybRAF0foRsQOnqnhdKMtlxQ7aYx5S1Gj_tERMBB1-lh8guSZsKJSPHvAHibJyJwKaGY9u_n7kVn6fK05NFAYg.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.정령,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "셰이디": {
    default: "https://i.namu.wiki/i/VXPnO9GAoBN-9xgeObKdFZSxmSsY-GR41MCe8xhDndGPxvrlSsMnHPh87wNFRlCWEuS2GGcdCpaPwYqKu45AYCresfmZ6eUScTeyFZkVBGGn8o1ME_4MKd-UsuYAw9q-3cWZxJkrMAx4EJqCLvMDpw.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.유령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "앨리스": {
    default: "https://i.namu.wiki/i/ECMEuzchUlAy0KLGFRv0XhJ6sIbegAJGQSwRyKeIF8BSdesvRJwUAo8uPdJ9xDHnpCQnNP_A9ZVXltV3HG9w7ru1tLJW7GpXf0WY5L2BRQErYX4ZCop13y5R1dFjCmQ5qrAiJ2Yqjg6g9m2aLm7Nsw.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.유령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "림(혼돈)": {
    default: "https://i.namu.wiki/i/6nxq0IXK-6t6v_xnUqlBFPyr1ykBVpc_BAuJZleTel-HHnyavZLRV_OMgXe1O5AZNOAu_0HdbAtNLytCmxYGv-M6hZdiYfBr1lnLgbuX1eiD8Rlf1mbD0xdUwWwrycALDs2qCCa09FxIgeIqbcW02g.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.유령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "메죵": {
    default: "https://i.namu.wiki/i/lqxelvRAWQsh2zeW3rHjqtJkj8nHaJcWk0q5lx5cfT6Uz_vWGzG6XgeP059xTQmNdvarDcrfWXF42POKXQfghSkx4YsVELWAqpHJMOtKwHJXWcvoGkQSNiuXuOw1RPmAPPAQtPuirLTYcX7vo52qJw.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.유령,
    rarity: BirthRarity.OneStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "실비아": {
    default: "https://i.namu.wiki/i/jzMD5chLq9mcy9WoYMB6zs-I5y18DEpoAnYjWrErR1RRL1gv0JCV-JIKWQPb34Lm0K6KSZqDcm0cpAfOTG7ATuT5k0u-rioIWMr8fQWpz7eZ_G7-z4Ca_Vy6DkOBYQcZS7-sot5RuoDaFfYwJoZOwg.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "네티": {
    default: "https://i.namu.wiki/i/6Er__7VYp5DwdKZwlavSiGXySM514imVkyo1iYt0Nq0SfjYY9req2LTBhrXCymR9qclfCfpyUVxC1MkXSMwebHeCOylObJXe3vJNRKwByOsnhibxO7JuucpEuJvPlaWgYvo1DcE7CAfwX8q6w7pDHA.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "리츠": {
    default: "https://i.namu.wiki/i/sNxGY88GIvnTw2wLf_CDMP9RcQwJmKsm0NG5V6FpGGYi4FGbB3BPfrQB6TOE2WHY4XnOtug5Jbpgm1E-mvhcWFtLxznZoW_hA8X20G-upEeinE7i9WiXrqk5zh4Icet0x0yaaWXEZh1nUt1q0v6hQQ.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "시스트": {
    default: "https://i.namu.wiki/i/uUAn7Dr8LL-KslF2_BLzKoMtnYtj7F75XU0-9DIKogYj1Ywdzi-38Ezs6jvqBul_PTlFKXKfms2Y6Mmoku1YctFq2ljDgqJIIz1uFst3JC4QLtXUjJuI03bnwq-Z2xxxoJoCt4Y9gIdPrgXyysgLfg.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "다야(퓨어샤인)": {
    default: "https://i.namu.wiki/i/6jCo1OXvFiwF9GZQjBhKEQ5anbhy511UHVgbFSAATZASbwFnMRpDwYIfSX9obJHSoJe66GSM-4XxTOepWk7LGVXAvS0UOZcb-F2Gy_YkQuR3XpWCBnNNMYt8bi-dIuPbiaj149RtUm2zZDdVLE0_0A.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "아네트": {
    default: "https://i.namu.wiki/i/G2LXfVgKT3ic84LH3ybmB3oSPuadiL4DhAk8mT-QTJ08JGpwAvLR7tUzjyHAS-Ui693yTubUWSyGzrZA1doMZKn47flw7VFZ3z7mugUUxIY7UXwoqCoQ3ZVxap-xk0znp64h8qk-NkvjnFVEDZ5YcA.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "피라": {
    default: "https://i.namu.wiki/i/RHV_ire_Fyfs9j-CaJ9eglRaO2tCWOh9rFdu7GG9iCZQ7__nBUBLYl4V5TtTa8KjR5tc7dS8WQaCIdCaNqHjD69eKT2nGNqEM4qWi6vU505VoglfrK41ECx4-VcZgBGZfMsVmujlQ0FizGkA8-sVYA.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "롤렛": {
    default: "https://i.namu.wiki/i/AnlGkPOVfyFj17pIpjKBUWJDF_Qr3gNc545RjxdT5gUAl7bE3HIy4GAhoZ0-TcqvIa2yITLSUwmkkTjpFHMITP-zOYH6709YZq3n_AerVRSJp68WW2jkQaO2ssVJj1pzOG2wsi4GxnWM_NCVy5Bn6Q.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.마녀,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "벨리타": {
    default: "https://i.namu.wiki/i/kLRwAgghE40VTyrMav7lL6gsmplpQq5d3YFtboyPJbRebv8qbVzHjG1Z8jAGGmESzIo20rDN0C3HYVCmWkxH_N7XzjXJKwLrE0RIlciq0qEv2qzHxW522yAYdF6nrDzTZdzGuBApfPp2AM7QJMIyDA.webp",
    personality: CharacterPersonality.광기,
    race: CharacterRace.마녀,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "네르(빡침)": {
    default: "https://i.namu.wiki/i/s9ibf4peuDsv3q0GsgUKq-338LVLTLvp6cPZ3-HAEq84k9uSoo3WXht6OQXpl0ZUz0NMYZEzYwIjTkmUbWkzdNQav0SB6NBozxnrjFSxfW-xWktMd0hzu9VJWcXAuEofd43f7blVN4XFEobWdWKXFQ.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "슈팡": {
    default: "https://i.namu.wiki/i/NpX_6vQk4Ejna9YTGoz0sl8S779iFKx2M6_-sYs1zbGwRLcicAgC6PLQJbkUmudsnxNTdEZKOAh390UIT6VfXNGIGqH8DqQO5CjSXzb-_dC4TfA5364IpEmVycDxQSYNi_VaZxaz2ZWNtMUofSgn7w.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "마리": {
    default: "https://i.namu.wiki/i/H1GNeQbZ-1nIOcIs-5BV6dWh4jSUliovkZYh1Ap4kXWPkHEjyPbmasr0ek5EvbwmwS3TUhM2N12iiV2UArNGc_Hyc-lGlZwZyhKrKr2iOqEXKJhnMVzN0hqYZc989DGSVtQZtsxP5Br7gTuPkbU5Ug.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.요정,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "카렌": {
    default: "https://i.namu.wiki/i/Czcb9CD37puBdOy6-fQbybeGF_mdEar1qibYQcKJCE-rh1VFPHs6qlaVZY1xHB8leIHbQbvvfzJaNIA6uIJt6Mp50_w_InzWmCsUKMvp8c2UMJrSkjpGGaRwavzi3ypSvJY3ONUFfRhIhr1YYgn19Q.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.요정,
    rarity: BirthRarity.OneStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "에피카": {
    default: "https://i.namu.wiki/i/E76ZiKj0qUdoR3Pix_VQVyvo4Fdlwn29Quo07tNMNuIAgcKq55zM-PnC0p22p3RyLQHzIM75hhexVNkbmwk3mK_G57ojRA06cC-WEN_wfPCiLILcstRKwSKssjk1N4UFrpjCwBbEaxTcKk-SlRpPyw.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "티그": {
    default: "https://i.namu.wiki/i/BOUenCnVW_qTg69I_SnKIah7A2RDjxiQdUTU5vCm7PijA9Tzr17nn4l__TkFZmHyMPaf0FJbke5HsVKB3OyIsdwBSw8eY2E5s7EzpTkxB5nwN4yjp8yfF4dUIY81wBA5k429Rf5ub_QnOr6wTjzu7A.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "루포": {
    default: "https://i.namu.wiki/i/YuU-lDB7UXyLbck9D8_-ZBA_hQk2Ijcb7nkkyv7kIIZhno74g4XnIhEezpxjB2Jg58QGO_TQxxdyawE75qvrq208P76l1of0t8VoEgig1woxg0bPuDbjYVXZEx2p6r1J1lS5Q1w6odoesJHxS6dWrw.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "모모": {
    default: "https://i.namu.wiki/i/3f5-c6SPCpFlGHmvQAb3mTSCZk6LrNkpW6j95y-L22ypExssYpwYnW5RkDZB8HGAvjnSrt-icboq_EejcduodEdTXWNvWdqwcs7gc_jyvx_l9zgFRLlTgL-WZ4c8ZfgzkNXQj8gdcIq8vvWBwzdVrQ.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "버터": {
    default: "https://i.namu.wiki/i/2jaQVVN4PPpdMyaIZ9pFRsRWETZIBH8frYR9dVVLzJ4_JZ7q14tzSyjWO1BlKFgBIAtIGlrLRyWc33MTUAqPFR7mIfnxJZLhaSmJZe2pND8X2WK3jLTcfzBZvy2yy7Kc454H8nUP2pXF7cYIsxV8UQ.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "슈로": {
    default: "https://i.namu.wiki/i/fdeO_d1a5QwLzm6WfAk87CILLv9T58QypbtAfPMGZuGjs6tGPMp0jmD711D8A5GbAW_9TjUR1ElcBTIdpo--lzGOKJwz0YLqWGzQbKlRtvDeSfljAjyjonfRVv3R7kP3DuwununM4m0KtKdazdESrQ.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.전열,
  },
  "바나": {
    default: "https://i.namu.wiki/i/KrE65Iv9t7HfURCtTVUd2eb9fRVT8-aCtwfm9V_xJQtDgiCgIX55iMIZ5PnHSh5zwc5OPPjidIK4_QnfNUvQ0MQkYfF7M5bBknXf_HFLRl8_kqyfQzZhpY5QMrnSN33_Wn05ZY537JwvvMxcFaolpw.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.수인,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "밍스": {
    default: "https://i.namu.wiki/i/wyVL3CEE8YSFAkOveRvCtVT9rggv89yic7LPJJyw8JSX6gQdc-4yLf7zVt2nag2DkkWCf_AuoJZXmxJF3yaTJzHYm75azJE1aavgE8X5ZcvY-fb-VLr_i7gN6zPAuulUhBaCAGF6U5wNaMatxLTo1Q.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.수인,
    rarity: BirthRarity.OneStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "칸나": {
    default: "https://i.namu.wiki/i/G2KLEGIYFpWO-E6u6eqZ6HsedF6BakErqtXvsxxFobmtuZejOBpx2G3GeQBXNTRSI6jZkUjw2WdaJ9_CxSBlSbDWBorE-aA-rjf_pHoQjsJegICOYow9Pmq9ebjR8tBW7JJIxPhKAzMy7PF-4DPXlQ.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "타이다": {
    default: "https://i.namu.wiki/i/9mnDhF0mYZgjqeRF2sQfj6HtQiNXoDWCrbJH1QqhI539MszR0sAOPs7epyeZ2700ClOChV1G3nPk_1eLwtUaGg0b2dUtQh7FKi1gTvG_ysbkUNgpJaLiswX5VZRpLrjC7QYQYHGxdPo2XfEBXMh77Q.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.엘프,
    rarity: BirthRarity.OneStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "우이": {
    default: "https://i.namu.wiki/i/N0QNrRkjcnpoTTpdTybqlAO2hwsHqQObjNlCafYyZ1BXfkPKB6sa1oSebYQj6muYBfLqU_zodqhfqXUUlyde0AtWuQWYdPlNRzS8qhoVMqsiGp-CPeS5HkhuNZ1zKU05GfwbQGmvAeU3Ko3Y88ZkMw.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.정령,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "미로": {
    default: "https://i.namu.wiki/i/wHSE-wMZeHB3wog1Qtzz9I-1Ip8iAG0HoPV8gYKsxhL6ERmnDBZbz-tDC8Zy8L-f0lIv0FI0Vmcbjt1dqGqn0XIN4zEVT4Hk7ed5Bx5x42lUWzVxrSsmZbl4wQbOcnxZDHtke348r4uEh5MXzUvi2A.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.정령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "아르코": {
    default: "https://i.namu.wiki/i/95MP40wJ5Wrc-LOfmv5xaRpJa9OoyM1nFwXUeUOsG5zIOtudE-TfxPhMwQOciUbqityGBYzVrW1chnUwGqjBlIC2nnSrL97DuHXKTFTgeSPXc576V2wJpx3Dvdic8ajTa-Hi6DJihAMm2gqeXQI3EQ.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.정령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "쥬비": {
    default: "https://i.namu.wiki/i/5UwMKu6jl65LxvBlolrlUZzKe8_8zmVGSnZh8Kfa9fhbZrqEfo9tED_a2RmqsP6hnJZYTQYkOjCQRk1-3Q5Q6k-kGNfki6NbsgrF5TkBPyhR1iJQI2lnbio8jLcjWXn2gw5G1MNfxYnihEN7nlrq7Q.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.정령,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "벨라": {
    default: "https://i.namu.wiki/i/2qqHtNVKir9qOaXN_vLFVou4dpZOjTEpoOrvxqJdtx25yEcxIAgq50fV7Ah3vgMVKe0qTbsgqR7D1B3a6LYXx-7DfyDU1TMV__OQkC78RuBRJSY_NMrDyU9f45xNCBZiwzTHjBRHfw7i5hnGqmHy8g.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.유령,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "셀리네": {
    default: "https://i.namu.wiki/i/iDQti_Rh_HE_pw3DrEFP5v2pBo39NDvhYJA4vo7CSWCpewKORHS2uMRb3P7ve43E4Z73576I4GIkKQqHZK9O60U25sDLmNZ1A9EPdsElKYEBshkIaslydy9UBt677Bpc2K6QyU17LpesFR5MHOVqWg.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.유령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "스피키(메이드)": {
    default: "https://i.namu.wiki/i/_Ui7gY9ctGnSIp1PJjeI2qY9HcoG5kb0F4fZoJ5RQ44V4TpZqDeExBFX148fMDrq90oybP8GC69I058Z5m54YfGno4bBFlPc2AnjfyUZDLLtmyj639kZ7qWSeX2PHtvBORQS2Sk2RnhlZI-rTQ1Opw.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.유령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "셰이디(역전)": {
    default: "https://i.namu.wiki/i/vL8-MbEfD0FzM_e9FUjk-M_fvG6QmS49lF5MtUtRHJpZAogIWX5QG5FBFvYyttReRLpWnArzE05Z9efeQ6aol1qFXg7CZEu8CsnakMurBem9TB5xym-fAscve5JzhbBW15eZW2KpSuruyNssh-5mBw.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.유령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "루드": {
    default: "https://i.namu.wiki/i/Owma1tA65R2IlJB7kPZAZbFDCYAjn4BIyjfG4z8fOKlSIwF3_1ses0IbK_GEwamLSDI72mJZCz1JshWAmhLs0q2CgjU3aUtD__tjDVhytH6UJSZLH34IEJrbFXcXlA38SEOyeKxkXNnbneI9SkBJsA.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "레비(졸업)": {
    default: "https://i.namu.wiki/i/qzPKbb4im6HEldDsRF9MxS88Rx2CJlFimgEeLNKsm7mSV5UKNkYvdUKEeG6aLbEQEfToMPDNbwkBdBHh1pgYV7ZmtxOIusRE_NJeGEvun6BZZ3to_MRqqOZ76pmauf89aEFKCLNCcKg_KOxfqwTgXQ.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.마녀,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "마카샤": {
    default: "https://i.namu.wiki/i/4xSs1jwlKLyn40DLTDj3zC0jK2mKUBnTh8d7mA88Y0hlCopkvLR3o5Vbw6yM2qrY_K14L4cthishSwM1fpfmu0CeDaN0berMfPqggG2WbnJnNwUwqGI9o9SfghhauK2TfCrXuZsDJvsConb6r9vgAg.webp",
    personality: CharacterPersonality.활발,
    race: CharacterRace.마녀,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "죠안": {
    default: "https://i.namu.wiki/i/WqHsScIpj9aSlY1qyM30V6ClY4u9ONDMsqACar3Xq72tnocD7SRyOPbXq37oYWfi8bF0d3kYMbyacese06PwKVJ56T6hJbNAmcjZNsJaqKQXOvqNemZ7sO0NTdKL4OBZqepDfIQhLEdPAMhVrehyMg.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.서포터,
    position: CharacterPosition.모든열,
  },
  "샤샤": {
    default: "https://i.namu.wiki/i/aJh-bC76IM95hv-cG1k9So4QXHSCL453GJlfbjszFy8sr720izeoIqoB9QAQw6RDSQ6YW3VEbn5OP-72aMs79Z6MSdHjiiZT42WYgjAbYKqxEhvrNRhZPu77RcsP8HkeOOuIGBddfatPBybcV5WceQ.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "에슈르": {
    default: "https://i.namu.wiki/i/g7xklH2Luldfe28wAClCbPSA0e7-VkaBOpE8kscHE2KewuK9syrAP5ZZXzg1tR7TF3o9HICeGHdhj9OS2dGdoPYDo7Slpt6AGFMtT5QLgdnx1XRk5uUweMgDa-p20GmcY7BE4C2QH0tusDeyiBjwrA.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.요정,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "리온": {
    default: "https://i.namu.wiki/i/bwbyE-bjxd2ZPaSNlDn94UKr4VYvmdYC0re28lItTYMgUp4ypbufo5UoaKWFiVZsEry2SpvDvB-R81phZO7AWclbiYpkhhuJuXj3hxkRyA0RG8jd4B717JnzlIGpAJBqYyuy1mLH4NbQEDTUpBiGIg.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "코미": {
    default: "https://i.namu.wiki/i/yQGQo9pc6EVwOQbUJu82zjxZn5Et956bmVSChfIVZvhDu3IXqqXeg9XY_f35PV5rPsy4ifmmNfZts2Zf8F3XH1Dah7EUIXd6vOrFZq4exR1GkWvSpDVB6oL_Br_XAqVF32i94imlhT4Zc6ppvaVYZw.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "쵸피": {
    default: "https://i.namu.wiki/i/NOMpmY5yezJQQsCbWX5DooIr4dQfgBi1r9sg7jV1zcV5oH8tZBj8IYAshgWJbP7NwvbrLMzpZ4lke5tkDcBDqS3G4n8kNiM-7_7KHxvv4ONO5MbppqMlx6h29ZgARPvdsAEiYmym8wliJnyYE6GfgA.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.수인,
    rarity: BirthRarity.OneStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "로네(시장)": {
    default: "https://i.namu.wiki/i/bPW5E5Psx78XVc8T4lSDe9UbbhDXVqirPFcrlmFRfcoKQQpZKunz0V3aPKAaZfaHv-YvqAfHe1XVvjXbGYsyfkb-PQje2ApiGPdwdPAlwb3IQS2FCxcBfZn9h-JT9KDk4f5s5-UHsIPE9gYIIrg2ZA.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "리스티": {
    default: "https://i.namu.wiki/i/PUscyMYMIzI9rMgIiAieHkPtEgfvZTO5u0Lwj-zNXL0w3RxnbH8zTAi2hrwILBGgksHObxEDpr3BqJr1wHA6NuP4QVmAdvKqmgwvkRSnRuClAMIxJTNRp_2Rn_Oza77YXftAWpsTP1itXGhdFyQsQQ.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.후열,
  },
  "힐데": {
    default: "https://i.namu.wiki/i/vqvS4nbSr5kRXG4QzrNA0zB_pc0Sn48zi6ko0nFWl6JkXGQKTCiRDmhRaKWjW0_a8shTbl-_dyzhQCV6FTqxQxk4EttrjbFFWr9_g-d8K0KitwsQnpsu-LZPIRyXchrCKsRAwV_IDixxwXcucHFibw.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "아멜리아(R41)": {
    default: "https://i.namu.wiki/i/I4gmhawuB2larjlQO40cuCd8E_QKpLLogL6SZ3cE48TP-b_0Zpxl_JWF_RpTa_oyXH7rEhfj23ZeBsZXJVuX0l5H9j9Y_vdAMZhLCat-mRnUiCr-Bf1USBmhdDETx35S1CAFH_vfCw2n7qBT4KkruQ.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "오르": {
    default: "https://i.namu.wiki/i/ZRrgxBGKydqq_9fK2WByujTqOb69w7ImA_oCaW5nwXtL6ryWZa9QwCw5BPbzD9qLngu3wAChKJRRz4gUBBeraCSgoTw89LKKyvBCWv7a6Twt8LkKLj_9mzzljmbmn2MeJ8xXLieKU4dfew-hWhvbMg.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.엘프,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "블랑셰": {
    default: "https://i.namu.wiki/i/om-pL9zkBrUhLuWS0MrcSFkNDO_xE8dhLg1fiC4xA_nMJHWu81_NpGhG-d0LyG4ECrdhwMBfOL9qOWzCtgpNmtSXo8WuhvhygZAMe-1U11wLOiqjx6yYmamrc249gAjpNv5W7jXb6xjkA9ANoCgBYw.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.정령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "시온 더 다크불릿": {
    default: "https://i.namu.wiki/i/ga0YSJEGK3D-Ja35gyLd08J9SnUBi8d81gv6zs1Y0Av_SAb4ulWTJvucYHC60FenqOhTk2zXglSbbhaXT8HKDMplJlk6JrkcSY4GdOERsuoAe_lSB4sPhr5Tfr4wyb0h_K498-2-DRTYuPunqfODhg.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.유령,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "림": {
    default: "https://i.namu.wiki/i/nSElpPVeSf7rHm4M1C96_cXNNzhu-9XFJX3UxwE7iFsrSjJbzpZoajyJYFBNAAEgqPGssT-yQDigeW_ODferNnaqKn8nqcPtg9UG-vder9-5Jg-1nxdkxjCaTE_OqiLpbsGe2wZV3EZKWn-GKxzMow.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.유령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "키샤": {
    default: "https://i.namu.wiki/i/je8LPLH-LZvPrLUbc4bcL59-tKESUD7dbkqUcJLLHW_58iQXcra3mgzJJm3PtlEASulROXc7Mk1ygwUBtG61KwrXGUJHOdevr6nM_BMbg083QhfglJTwFQD-lWRbjm35GrlsHK-ZhE1niGvLhMoYtA.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.유령,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.중열,
  },
  "베루": {
    default: "https://i.namu.wiki/i/HRzYL973DZz_VSfKMBeYdr0Xdzuboi1m4mBRG9Jl150Mt4xE178GLWJEQYtAafopSP0f1eByKG067KBbWvWB4PoPPgg_K1iiTvN7l36v6mb7yW4NnDsMzqOo5rAVr4Qa_KLBlrY4E31cnH9ufrECYA.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.유령,
    rarity: BirthRarity.OneStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "키디언": {
    default: "https://i.namu.wiki/i/v8OvDsfkY7ZotdjW_mg9jMms2d91SDCnFEGCfg-9fEPmYnvQ0mmc9G7rDLZD8XZttinZvX_AOCqgrUZxovZS2q2VF554B3qP7TfPN0Zpb5uurLgH-j7UZ-xr2y72-F7STjiis3zCiPpzLMGaocq24A.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.용족,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.전열,
  },
  "실피르": {
    default: "https://i.namu.wiki/i/ySr334wqXSURejhkeddn2ME37mkRfptJzokhXYzjqXm5wnpztYHVQ79O9cCYRG16CP4mImK3QzYismXi4Eu1KvyuFqCHTUJK7pwRWACbKTbjp33-HWHmwEPgBu5W41GVDryKKBAScMORPs7QdIikEg.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.용족,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "스노키": {
    default: "https://i.namu.wiki/i/WMHtL2lnZMU7gRYmtfrG8k0ciTLCoiUfnATZn5ulO_xOevVt7hUov7xHQwod-7kylcOrWYICqZnNY4ZbKL5PEvjgQRoLZcFdiDR_szAkQYjRR4C4xMAmzMGTyL2mX02ESRsbG1TiGPirF_ZE08rEMw.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.마녀,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "아사나": {
    default: "https://i.namu.wiki/i/aGS4WRd7ISSol0_z7T_dCWuob-kxnYkEiIErND9HMRr_x7AD_6LtdIQ4tTYBA4cFTSxQkf2C46rblfIh3Q-z9wdpDQ7C3MfeYrQjEtCJBadYQT9Bmh4YoXbrT80Wj40LzDnoN2KGz4Mz8UeXJihSRQ.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.마녀,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.탱커,
    position: CharacterPosition.전열,
  },
  "포셔": {
    default: "https://i.namu.wiki/i/qGYkgTOPdp-UBIJ9G990-7uIF9JBpvNKpjGvcgsLnjGtxcWR0mNlJv4FqDNcsN3LoNOjVQmDN6b8VIOL4IgvlQTPFZq4PBnG-NnC7Q1fryR1ex_EVrSIuzIUdFW4jEpaSOj7L8_wS3OvPa0wBxVliQ.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.마녀,
    rarity: BirthRarity.ThreeStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "레비": {
    default: "https://i.namu.wiki/i/UzitLtswgOpNw9RuSK3fhJyjJeIZI8H52k7iC2AZL0nXztP_oXWtD8Y9XY5DORwm3V3gO0w4MS-i5aMlnaoMpshggY216KRlo3bZRGmRXFa7J3iOztMp7K2Nbp12ThK3m0KB2nu4ZNLdXsfXOunIrA.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.마녀,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "바리에": {
    default: "https://i.namu.wiki/i/XSa3Jgh-EVK6Buskrsr9UAJ55YBpcFO-KGPhJ6Y6Sb161uzsqJklXBZHgOU2AVRLv-ZVPfgxw9dWw4D__gdNBCt57Hcvn11ZLA_9OxiFyKDMX6ZDH5mtrkokoKzy485pDPYsSIKhG7I4rrnripNd0w.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.마녀,
    rarity: BirthRarity.TwoStar,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
  "요미": {
    default: "https://i.namu.wiki/i/FP5_EBxObkRb3k6exC32HnCQ-UQugEGf4-JaCQFowm_wfywcVMeLA0gIrCTd4nvKW3hP3RhKyRVAjPsKgI31PEtG9lEv9aWEUR9_EzjhRlDl-sy5DInCwYSgzYB2rRXrjZBl2J56YHZrDq6tgoeQmA.webp",
    personality: CharacterPersonality.우울,
    race: CharacterRace.미스틱,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.딜러,
    position: CharacterPosition.중열,
  },
  "우로스": {
    default: "https://i.namu.wiki/i/1SAcKxIcPVPRH-UjbKwhsRJyNYk473MZF7oWWxrQz7PoN7ePdKxdNB8tGZs1FoT7TI9OTdSIjk7LSQ4aXV6F05EzNNSyvpcMgQSGCtaNqCEh8DmHwGfkVBYFypbLEU4OgpTt5SbecC0P_GM5ctzpWQ.webp",
    personality: CharacterPersonality.공명,
    race: CharacterRace.수인,
    rarity: BirthRarity.ThreeStarEldain,
    role: CharacterRole.서포터,
    position: CharacterPosition.후열,
  },
};